name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Ur requirements.txt
    - name: Install dev dependencies
      run: |
        pip install -Ur dev_requirements.txt
    - name: Lint
      run: python -m pylint ./envpy/*.py
    - name: Test
      run: python -m nose -s
